name: Android CI

on:
  pull_request:
    branches-ignore:
      - ''
  push:
    branches-ignore:
      - ''
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Download lib/Mobile.arr
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: ffip,
               repo: mobileVLAN,
               run_id: 6135920331,
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "libx.aar"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: ffip,
               repo: mobileVLAN,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/libx.aar.zip', Buffer.from(download.data));

    - name: Unzip lib/Mobile.arr
      run: |
        unzip libx.aar.zip
        mv libx.aar app/libs/Mobile.aar
        rm libx.aar.zip

    - name: Build Signed Release APK
      uses: victorbnl/build-signed-apk@main
      with:
        keystore_file: key-store.jks
        keystore_password: 666666
        key_alias: hiper-key
        key_password: 666666

    - name : upload apk
      uses: actions/upload-artifact@v3
      with:
        name: HiPer
        path: app/build/outputs/apk/release/app-release.apk
